import {StatusBar, StyleSheet} from "react-native";
export const styles = StyleSheet.create({
    container:{
        flex:1,
    },
    languages:{
        flexDirection:'row',
        alignSelf:'center',
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        top:StatusBar.currentHeight?StatusBar.currentHeight + 18: StatusBar.currentHeight!== undefined? StatusBar.currentHeight+58:0
    },
    langButton:{
        borderWidth:1,
        padding:4,
        borderRadius:4,
        marginRight:4,
        marginLeft:4
    },
    langText:{
        marginRight:4,
        marginLeft:4,
        color:'#fff'
    },
    logo:{
        maxWidth:200,
        height:200,
        alignSelf:'center',
        marginBottom:44,
        marginTop:'35%'
    },
    title:{
        color:'#fff',
        fontWeight:'bold',
        fontSize:30
    },
    button:{
        alignSelf:'center',
        backgroundColor:'#037CFC',
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:10,
        borderRadius:6,
        marginTop:28
    },
    buttonText:{
        color:"#fff"
    },
    linkButton:{
        marginTop:14,
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    linkText:{
        color:'#fff',
        textAlign:'center'
    }
})